[package]
name = "helioxide"
version = "0.4.0"
edition = "2024"
description = "Rust implementation of NREL Solar Position Algorithm (SPA)"
repository = "https://github.com/Kuenlun/helioxide"
authors = ["Juan Luis Leal Contreras <kuenlunleal@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["solar", "spa", "astronomy", "sun", "nrel"]
categories = ["science", "mathematics"]

[package.metadata.lockpick]
license-header = ".github/license_header.rs"

[dependencies]
chrono = "0.4.44"
chrono-tz = "0.10.4"
thiserror = "2.0.18"

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
debug = false
