name: Rust

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Install lockpick
        run: cargo install --git https://github.com/Kuenlun/lockpick
      - name: Run checks
        run: lockpick
